name: "Liferay Build"
description: >
  Build your Liferay workspace (Gradle or Maven), and create the bundle and artifacts to be used later.
author: "lgdd"
branding:
  icon: "loader"
  color: "blue"

inputs:
  java-version:
    description: >
      Java version (default: '11')
      Check Liferay compatibility matrix: https://www.liferay.com/compatibility-matrix.
    required: false
    default: "11"
  java-distribution:
    description: >
      Java distribution (default: 'zulu')
      List of supported distributions for the setup-java action: https://github.com/actions/setup-java#supported-distributions
      Also check Liferay compatibility matrix: https://www.liferay.com/compatibility-matrix
    required: false
    default: "zulu"
  profile:
    description: >
      Name of the config folder corresponding to the environment it should be build for (e.g. local, uat, prod).
    required: true
  workspace-directory:
    description: >
      Path to your workspace if different from root directory.
      It will be use in this actions steps for the 'working-directory' directive.
    required: false
    default: .
  upload-bundle:
    description: >
      Boolean to determine if the bundle should be uploaded in the workflow (e.g. to be used in a release).
    required: true
  upload-artifacts:
    description: >
      Boolean to determine if all modules (e.g. client extensions, osgi modules, themes) should be uploaded in the workflow (e.g. to be used in a release).
    required: true
  retention-days:
    description: >
      Number of days to retain uploaded artifacts (i.e. bundle and modules) in the workflow (default: '7').
      More information: https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization
    required: false
    default: "7"

outputs:
  bundle-path:
    description: "Relative path from the workspace to the archived bundle"
    value: ${{ steps.create-bundle.outputs.bundle-path }}

runs:
  using: composite
  steps:
    - name: Detect Build Tool
      id: detect-build-tool
      shell: bash
      working-directory: ${{ inputs.workspace-directory }}
      run: |
        if [ -f "pom.xml" ]; then
          echo "tool=maven" >> "$GITHUB_OUTPUT"
        else
          echo "tool=gradle" >> "$GITHUB_OUTPUT"
        fi;
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: "${{ steps.detect-build-tool.outputs.tool }}"
    - name: Set up Blade
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/liferay/liferay-blade-cli/master/cli/installers/local | bash
        echo "/home/runner/jpm/bin" >> $GITHUB_PATH
    - name: Build Liferay Workspace
      shell: bash
      working-directory: ${{ inputs.workspace-directory }}
      run: |
        if [ ${{ steps.detect-build-tool.outputs.tool }} == "maven" ]; then
          mvn clean install
        else
          ./gradlew build
        fi;
    - name: Create Bundle
      if: ${{ inputs.upload-bundle == 'true' }}
      id: create-bundle
      shell: bash
      working-directory: ${{ inputs.workspace-directory }}
      run: |
        if [ ${{ steps.detect-build-tool.outputs.tool }} == "maven" ]; then
          mvn bundle-support:deploy
          mvn bundle-support:dist -Dliferay.workspace.environment=${{ inputs.profile }}
          bundleName=$(ls target)
          echo "bundle-path=${{ inputs.workspace-directory }}/target/$bundleName" >> "$GITHUB_OUTPUT"
        else
          ./gradlew deploy
          ./gradlew distBundleZip -Pliferay.workspace.environment=${{ inputs.profile }}
          bundleName=$(ls build | grep ".zip")
          echo $bundleName
          echo "bundle-path=${{ inputs.workspace-directory }}/build/$bundleName" >> "$GITHUB_OUTPUT"
        fi;
    - name: Create Artifacts
      if: ${{ inputs.upload-artifacts == 'true' }}
      id: create-artifacts
      shell: bash
      working-directory: ${{ inputs.workspace-directory }}
      run: |
        mkdir -p bundles/deploy
        mkdir -p bundles/osgi/modules
        mkdir -p bundles/osgi/client-extensions
        if [ ${{ steps.detect-build-tool.outputs.tool }} == "maven" ]; then
          mvn bundle-support:deploy
        else
          ./gradlew deploy
        fi;
        if [ -n "$(ls -A bundles/osgi/modules)" ]; then
          mv bundles/osgi/modules/* bundles/deploy
        fi;
        if [ -n "$(ls -A bundles/osgi/client-extensions)" ]; then
          mv bundles/osgi/client-extensions/* bundles/deploy
        fi;
    - name: Upload Bundle
      if: ${{ inputs.upload-bundle == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: bundle--jdk-${{ inputs.java-version }}
        path: ${{ steps.create-bundle.outputs.bundle-path }}
        retention-days: ${{ inputs.retention-days }}
        overwrite: true
    - name: Upload Artifacts
      if: ${{ inputs.upload-artifacts == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: artifacts--jdk-${{ inputs.java-version }}
        path: ${{ inputs.workspace-directory }}/bundles/deploy
        retention-days: ${{ inputs.retention-days }}
        overwrite: true
